import assert from 'node:assert/strict';
import { startOfWeek, endOfWeek, format, addWeeks, startOfMonth, endOfMonth } from 'date-fns';

export async function testProtectedDashboard(page, open) {
  await open('protected');
  const filter = page.getByRole('region', { name: 'Perioada statisticilor' });
  await filter.waitFor();
  const month = filter.getByRole('button', { name: 'Luna curentă', exact: true });
  const week = filter.getByRole('button', { name: 'Săptămână', exact: true });
  const all = filter.getByRole('button', { name: 'Tot istoricul', exact: true });
  const lastRange = () => page.evaluate(() => window.__inputTest.overviewCalls.at(-1));
  const iso = date => format(date, 'yyyy-MM-dd');
  const now = new Date();
  const currentWeek = { from: iso(startOfWeek(now, { weekStartsOn: 1 })), to: iso(endOfWeek(now, { weekStartsOn: 1 })) };
  await page.getByText('£120.00', { exact: true }).waitFor();
  assert.equal(await month.getAttribute('aria-pressed'), 'true');
  assert.deepEqual(await lastRange(), { from: iso(startOfMonth(now)), to: iso(endOfMonth(now)) });
  await week.focus(); await page.keyboard.press('Enter');
  await page.getByText('£70.00', { exact: true }).waitFor();
  assert.deepEqual(await lastRange(), currentWeek);
  await filter.getByRole('button', { name: 'Săptămâna anterioară', exact: true }).click();
  await page.getByText('£70.00', { exact: true }).waitFor();
  const previous = { from: iso(addWeeks(startOfWeek(now, { weekStartsOn: 1 }), -1)), to: iso(addWeeks(endOfWeek(now, { weekStartsOn: 1 }), -1)) };
  assert.deepEqual(await lastRange(), previous);
  await page.locator('aside').getByRole('button', { name: 'Facturi', exact: true }).click();
  await page.locator('aside').getByRole('button', { name: 'Dashboard', exact: true }).click();
  await page.getByText('£70.00', { exact: true }).waitFor();
  assert.deepEqual(await lastRange(), previous, 'navigation retains filter in memory');
  await filter.getByRole('button', { name: 'Săptămâna curentă', exact: true }).click();
  await page.getByText('£70.00', { exact: true }).waitFor();
  assert.deepEqual(await lastRange(), currentWeek);
  await all.click(); await page.getByText('£999.00', { exact: true }).waitFor();
  assert.deepEqual(await lastRange(), { from: undefined, to: undefined });
  await week.click(); await page.getByText('£70.00', { exact: true }).waitFor();
  await all.click(); await week.click();
  await page.waitForTimeout(350);
  assert.equal(await page.getByText('£999.00', { exact: true }).count(), 0, 'late old response must not replace current range');
  await page.getByText('£70.00', { exact: true }).waitFor();
  await page.evaluate(() => window.__inputTest.setOverviewFailure(true));
  await month.click(); await page.getByRole('alert').filter({ hasText: 'Statistici indisponibile' }).waitFor();
  assert.equal(await page.getByText('£70.00', { exact: true }).count(), 0, 'failed range must not retain old statistics');
  await page.evaluate(() => window.__inputTest.setOverviewFailure(false));
  await week.click(); await page.getByText('£70.00', { exact: true }).waitFor();
  await page.getByText('Rest de plată actual · Tot istoricul', { exact: true }).first().waitFor();
  assert.deepEqual(await page.evaluate(() => ({ local: { ...localStorage }, session: { ...sessionStorage } })), { local: {}, session: {} });
  await page.locator('aside').getByRole('button', { name: 'Blochează și ieși' }).click();
  await page.getByLabel('PIN', { exact: true }).waitFor();
  assert.equal(await filter.count(), 0);
  console.log('PASS protected dashboard: current month, Monday-Sunday, week navigation, all history, keyboard, stale/error responses, memory-only and lock');
}
