name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm install

      - name: Build App Assets
        run: npx vite build

      - name: Build Electron Windows Package
        run: npx electron-builder --win --x64 -p never

      - name: Publish Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          files: |
            release/*.exe
            release/*.blockmap
            release/latest.yml
          draft: false
          prerelease: false
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
